[package]
name = "poltergeist"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
base64 = "0.22.1"
config = "0.15.19"
jsonwebtoken = "10.3.0"
moka = "0.12.13"
reqwest = "0.13.1"
rsa = "0.9.10"
serde = "1.0.228"
serde_json = "1.0.149"
sha2 = "0.10.9"
tokio = "1.49.0"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
