issuer: "http://localhost:8080"
grant_types_supported:
  - "authorization_code"
  - "client_credentials"
port: 8080
upstream_oidc_url: "http://upstream-idp/auth"
upstream_jwks_url: "http://upstream-idp/.well-known/jwks.json"
validate_upstream_token: false
private_key_path: "test/private_key.pem"
clients:
  - client_id: "zeebe-worker"
    client_secret: "zeebe-secret"
    groups:
      - "camunda-admin"
    audience: "zeebe-service"
  - client_id: "camunda-web"
    client_secret: "public" # Poltergeist currently requires a secret in config, but we can ignore it for browser flows
    groups: []
    audience: "camunda-identity"